//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.JNP.JQ {
    
    
    public partial class FinalJQ {
        
        /// <summary>
        /// mainAJAXManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadAjaxManager mainAJAXManager;
        
        /// <summary>
        /// ctrlJQFinalInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HCMS.JNP.Controls.JQ.ctrlJQFinal ctrlJQFinalInfo;
        
        /// <summary>
        /// ctrlJQFinalDetailsInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HCMS.JNP.Controls.JQ.ctrlJQFinalDetails ctrlJQFinalDetailsInfo;
    }
}
