//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.PDExpress.CreatePD {
    
    
    public partial class PDTypeChoice {
        
        /// <summary>
        /// ctrlPDChoice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HCMS.PDExpress.Controls.CreatePD.CreatePDChoice ctrlPDChoice;
    }
}
